# Generated by Django 3.0.3 on 2021-04-05 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc_flow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc_flow.Subject'),
        ),
        migrations.AlterField(
            model_name='document',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc_flow.Student'),
        ),
        migrations.DeleteModel(
            name='DocSub',
        ),
    ]
