# Generated by Django 3.0.3 on 2021-05-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_flow', '0003_auto_20210508_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_type',
            field=models.CharField(default='student', max_length=7),
            preserve_default=False,
        ),
    ]
